#!/usr/bin/env bash

# Copyright (c) 2021-2026 community-scripts ORG
# Author: pshankinclarke (lazarillo)
# License: MIT | https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE
# Source: https://valkey.io/

source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

CONNECTION_MODE="standard"
VALKEY_TCP_ENABLED="yes"
VALKEY_TLS_ENABLED="no"
VALKEY_TCP_PORT="6379"
VALKEY_TLS_PORT=""
VALKEY_TLS_CERT_TYPE="none"

msg_info "Installing Valkey"
$STD apt update
$STD apt install -y valkey openssl
sed -i 's/^bind .*/bind 0.0.0.0/' /etc/valkey/valkey.conf

PASS="$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c32)"
echo "requirepass $PASS" >> /etc/valkey/valkey.conf
echo "$PASS" >~/valkey.creds
chmod 600 ~/valkey.creds

MEMTOTAL_MB=$(free -m | grep ^Mem: | awk '{print $2}')
# reserve 25% of a node type's maxmemory value for system use
MAXMEMORY_MB=$((MEMTOTAL_MB * 75 / 100))

echo "" >> /etc/valkey/valkey.conf
echo "# Memory-optimized settings for small-scale deployments" >> /etc/valkey/valkey.conf
echo "maxmemory ${MAXMEMORY_MB}mb" >> /etc/valkey/valkey.conf
echo "maxmemory-policy allkeys-lru" >> /etc/valkey/valkey.conf
echo "maxmemory-samples 10" >> /etc/valkey/valkey.conf
msg_ok "Installed Valkey"

echo
echo -e "${TAB3}Valkey Connection Mode"
echo -e "${TAB3}1) Standard - TCP on port 6379"
echo -e "${TAB3}2) Dual     - TCP on port 6379 and TLS on port 6380"
echo -e "${TAB3}3) TLS-only - TLS on port 6379, plain TCP disabled"
read -r -p "${TAB3}Select connection mode [1]: " connection_choice
connection_choice="${connection_choice:-1}"

case "$connection_choice" in
  1)
    CONNECTION_MODE="standard"
    VALKEY_TCP_ENABLED="yes"
    VALKEY_TLS_ENABLED="no"
    VALKEY_TCP_PORT="6379"
    VALKEY_TLS_PORT=""
    VALKEY_TLS_CERT_TYPE="none"
    msg_ok "Configured standard mode: TCP on port 6379"
    ;;
  2|3)
    msg_info "Configuring TLS for Valkey..."

    create_self_signed_cert "Valkey"
    TLS_DIR="/etc/ssl/valkey"
    TLS_CERT="$TLS_DIR/valkey.crt"
    TLS_KEY="$TLS_DIR/valkey.key"
    chown valkey:valkey "$TLS_CERT" "$TLS_KEY"

    if [[ "$connection_choice" == "3" ]]; then
      CONNECTION_MODE="tls-only"
      VALKEY_TCP_ENABLED="no"
      VALKEY_TLS_ENABLED="yes"
      VALKEY_TCP_PORT=""
      VALKEY_TLS_PORT="6379"
      VALKEY_TLS_CERT_TYPE="self-signed"

      {
        echo ""
        echo "# TLS configuration generated by Proxmox VE Valkey helper-script"
        echo "port 0"
        echo "tls-port 6379"
        echo "tls-cert-file $TLS_DIR/valkey.crt"
        echo "tls-key-file $TLS_DIR/valkey.key"
        echo "tls-auth-clients no"
      } >> /etc/valkey/valkey.conf

      msg_ok "Configured TLS-only mode: TLS on port 6379"
    else
      CONNECTION_MODE="dual"
      VALKEY_TCP_ENABLED="yes"
      VALKEY_TLS_ENABLED="yes"
      VALKEY_TCP_PORT="6379"
      VALKEY_TLS_PORT="6380"
      VALKEY_TLS_CERT_TYPE="self-signed"

      {
        echo ""
        echo "# TLS configuration generated by Proxmox VE Valkey helper-script"
        echo "tls-port 6380"
        echo "tls-cert-file $TLS_DIR/valkey.crt"
        echo "tls-key-file $TLS_DIR/valkey.key"
        echo "tls-auth-clients no"
      } >> /etc/valkey/valkey.conf

      msg_ok "Configured dual mode: TCP on port 6379 and TLS on port 6380"
    fi
    ;;
  *)
    msg_error "Invalid connection mode selected"
    exit 1
    ;;
esac

systemctl enable -q --now valkey-server
systemctl restart valkey-server

motd_ssh
customize
cleanup_lxc
